### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by yupii1986** [chiraggude/stage#3]
Hello,
Nice work..
Can you help me with some stuff extra in this theme (extra stuff in theme option)

Thank you verry much.

**Comment by yupii1986** [comment]
Hello,
Can you help how to add option in page to hide show my page title?

Thank you

**Comment by chiraggude** [comment]
Hey, 

Since you want to show/hide the page title, you can:
- Leave the title field empty when you create a page
- Use this plugin: https://wordpress.org/plugins/hide-title/
- Learn the redux options framework to add the option yourself: https://wordpress.org/plugins/redux-framework/

Hope that helps :)

**Comment by yupii1986** [comment]
Thanks , i want to make this as option from my page not with plugin. I want to lern how.

Thank you

**Comment by chiraggude** [comment]
The options panel in the theme were created with: https://wordpress.org/plugins/redux-framework/
To add more options to the theme, you will have to read the docs. of Redux Framework and do it yourself. More specifically, you can read this to create a toggle option to show/hide some text (eg. page title) - https://docs.reduxframework.com/core/fields/switch/

**Comment by yupii1986** [comment]
Hi,
I solve that,
Now i try to include social icons and typography.
Can you help me ?
for typo i have added in theme admin http://collabedit.com/39fcs  but i don't understand from redux doc what to do next

and for social, i have this code in my social.php file  
                    <?php $facebook = ro_get_option('facebook'); 
                    if (!empty ($facebook) && ro_get_option('facebook')) { ?>
                    <a itemprop="url" class="facebook" title="facebook" href="<?php echo esc_url( $facebook ); ?>">
                        <i class="fa fa-facebook" aria-hidden="true"></i><span class="screen-reader-text">Facebook</span>
                    </a>
                    <?php } ?>

issue is with this: <?php $facebook = ro_get_option('facebook'); 

can you help me how has to be <?php $facebook = ro_get_option('facebook');   to work with redux?

Also i added some option in my redux admin

(i have a theme with smof and i add from there some infos but i modifyed them to redux.. some of them are ok, but ones i don't know how)

**Comment by chiraggude** [comment]
You're having trouble working with Redux and not this theme. I would encourage you to get help here: https://wordpress.org/support/plugin/redux-framework

**Comment by yupii1986** [comment]
And you can't help me? they dont respond.

**Comment by yupii1986** [comment]
or can you help me to add typography and social icons in your theme? How much will cost me for them?
